version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: samuel
      MONGO_INITDB_ROOT_PASSWORD: Mongo1234Ejemplo2024
      MONGO_INITDB_DATABASE: categorias
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: samuel
      ME_CONFIG_MONGODB_ADMINPASSWORD: Mongo1234Ejemplo2024
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - mongo-network

volumes:
  mongodb_data:

networks:
  mongo-network:
